### ISSUE TITLE
required username for single tenant

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#1]
why is the username required for a single tenant configuration?

**Comment by ticky74** [comment]
Yeah that's a good point. I've never actually worked with the single tenant configuration. I'll see if I can put that in over the next couple of days. I think the experience you are thinking is to simply click a Office365 logo or something then be cleanly redirected. Is that correct or did you mean something else. Thanks for the feedback.
ian

**Comment by mdissel** [comment]
Yes! Maybe even in a multi tenant configuration redirecting to an Office365 authentication could be an option.

Thanks

**Comment by ticky74** [comment]
Thanks for the feedback, this has been [committed](https://github.com/ticky74/ServiceStack.Authentication.Azure/commit/dd6a2d9c1d88b6940a28015e90a9c8a9acbb0522)

See the [wiki](https://github.com/ticky74/ServiceStack.Authentication.Azure/wiki/Customize-Login-Experience) for an example on using a custom ApplicationDirectoryResolver.
