### ISSUE TITLE
configurable redirect after logout

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#3]
https://github.com/ticky74/ServiceStack.Authentication.Azure/blob/master/src/ServiceStack.Authentication.Azure/AzureAuthenticationProvider.cs#L149

```
var request = MsGraph.AuthorizationUrl + "/logout?client_id={0}&post_logout_redirect_uri={1}"
             .Fmt(clientId, "http://www.google.com");
```

Currently it's fixed to redirect to google.com.

**Comment by ticky74** [comment]
umm oops. Sorry not sure how that got through.
