### ISSUE TITLE
Add security groups to the usersession roles like in the windows authentication provider

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#4]
We could re-use the assigned security-groups and assign them to the user like in the windows authentication provider.

see https://github.com/ServiceStack/ServiceStack/blob/9773b7fccc31ac4d715a02221f396b46cd14d7db/src/ServiceStack/Auth/AspNetWindowsAuthProvider.cs#L126

**Comment by ticky74** [comment]
In our case I guess we we would need to define them based on each tenant. Could add the list of security groups to the ApplicationRegistration for each tenant, that would be static compile time, or if you are registering tenants dynamically provide a hook their too. How were you thinking of defining the groups per user? I think its a good idea in general though.

**Comment by mdissel** [comment]
See the code in the Windows authentication provider. You can define the valid roles in the provider.

**Comment by ticky74** [comment]
I think in the case of Azure active directory, since we should support a multi-tenant app on the ServiceStack side we should add a hook on the provider instead of a static list of roles. Different directories will define different roles. Then each implementation can determine where they want to retrieve their security groups from. Would this work in your use case?
ian

**Comment by mdissel** [comment]
So we could make it part of the IApplicationRegistryService implementation. 

```
        /// <summary>
        /// Specify all roles to be used by this application
        /// </summary>
        public List<string> AllRoles { get; set; }

        /// <summary>
        /// Only allow access to users in specified roles
        /// </summary>
        public List<string> LimitAccessToRoles { get; set; }

        public bool AllowAllWindowsAuthUsers
        {
            get { return LimitAccessToRoles == null; }
            set { LimitAccessToRoles = null; }
        }
```

**Comment by ticky74** [comment]
Didn't add the AllRoles idea. Right now the provider grabs the groups from active directory. If there are any values in LimitAccessToRoles then there must be a matching value retrieved from the directory or the user is not authenticated.
