### ISSUE TITLE
An item with the same key has already been added. Key: ClientId

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#5]
I think this errors depends a bit on which scope the provider is registered, but with an easy fix that doesn't matter any more

[Authenticate: 12-4-2017 14:23:58]: [REQUEST: {provider:ms-graph}] System.ArgumentException: An item with the same key has already been added. Key: ClientId at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at ServiceStack.Authentication.Azure.AzureAuthenticationProvider.RequestCode(IServiceBase authService, Authenticate request, IAuthSession session, AuthUserSession userSession, IAuthTokens tokens) at ServiceStack.Authentication.Azure.AzureAuthenticationProvider.Authenticate(IServiceBase authService, IAuthSession session, Authenticate request) at ServiceStack.Auth.AuthenticateService.Authenticate(Authenticate request, String provider, IAuthSession session, IAuthProvider oAuthConfig) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Auth/AuthenticateService.cs:line 284 at ServiceStack.Auth.AuthenticateService.Post(Authenticate request) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Auth/AuthenticateService.cs:line 145 at lambda_method(Closure , Object , Object ) at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack/Host/ServiceRunner.cs:line 107

**Comment by ticky74** [comment]
Fix pushed 1.1.3
