### ISSUE TITLE
rename me.PhoneNumber to me.MobileNumber

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#7]
It will be a breaking change..

**Comment by ticky74** [comment]
Hi Marco,
I've been really really busy with work. Are you interested in commit access to the repo? You've been doing a lot of work on it and it would be great if we could get it all in there. Drop me a line ikulmatycki@gmail.com and we can discuss.

Thanks for your contributions.
ian

**Comment by ticky74** [comment]
Done
