### ISSUE TITLE
scope prefix is invalid

### ISSUE THREAD

**Issue by mdissel** [ticky74/ServiceStack.Authentication.Azure#9]
the https://msgraph.microsoft.com/ should not be added to every scope, the openid, offline_access, profile and email should be used without prefix. The others have a specific prefix.

https://docs.microsoft.com/nl-nl/azure/active-directory/develop/active-directory-v2-scopes#scopes-and-permissions

**Comment by mdissel** [comment]
"https://graph.microsoft.com/User.Read" is required to get an access_token to call the Graph API.

**Comment by ticky74** [comment]
Done
